### ISSUE TITLE
Change docker hub references to registry.devshift or registry.centos

### ISSUE THREAD

**Issue by anmolbabu** [fabric8-hdd/supervisor#2]
All references to docker hub registry in pipeline/jenkins files need to changed to registry.devshift.net
along with names of jenkins ENV variables that store credentials..

This was done only for ease of verification

**Comment by devang-gaur** [comment]
Hey guys, we can also go for registry.centos.org. The OSIO production container images are hosted on this registry.

**Comment by anmolbabu** [comment]
Closing this issue as the PR to fix this has been merged
