### ISSUE TITLE
Change container image repository

### ISSUE THREAD

**Issue by devang-gaur** [fabric8-hdd/supervisor#24]
https://github.com/fabric8-hdd/supervisor/blob/0acb50e25972b9be437de787f881b87f236825e8/Makefile#L1

We also need to make corresponding changes in the Dockerfiles

**Comment by anmolbabu** [comment]
Closed duplicate of https://github.com/fabric8-hdd/supervisor/issues/2

**Comment by devang-gaur** [comment]
oh
