### ISSUE TITLE
Make route hostname and service port configurable

### ISSUE THREAD

**Issue by anmolbabu** [fabric8-hdd/supervisor#25]
Make oc route hostname and service port configurable via ENV vars

**Comment by devang-gaur** [comment]
Isn't this a part of the umbrealla of issue #41 now ?

**Comment by anmolbabu** [comment]
No good that you reminded me of this.
This is an older issue than #41 will remove items related to this from #41

**Comment by anmolbabu** [comment]
Closing this as the PR to fix this has been merged
