### ISSUE TITLE
Change the docker image base to CentOS and ensure it sets user to non-root

### ISSUE THREAD

**Issue by anmolbabu** [fabric8-hdd/supervisor#30]
As per https://docs.google.com/document/d/14rKA_Uxve5f_mFNK4vhKhXrMcquiy25AQ5tpHJQwtbc/edit#heading=h.2r3a4udhggjl

**Comment by anmolbabu** [comment]
- [x] Modifications in Dockerfile

- [x] Modifications in Dockerfile.tests

**Comment by devang-gaur** [comment]
For the CentOS registry builds, a seperate Dockerfile.centos is maintained AFAIK. Dockerfile and Dockerfile.centos can be same (depends on us).

**Comment by anmolbabu** [comment]
@dev-gaur I feel this is required if we are targeting to support multiple OS as base but what is the advantage of doing so for a container application like ours is something I would like to know..
Note: I tried observing what 
1. Fabric8-UI does (https://github.com/CentOS/container-index/blob/master/index.d/fabric8.yml) there also no CentOS specific Dockerfile

Mattermost uses branches (https://github.com/CentOS/container-index/blob/master/index.d/mattermost.yml) to maintain separate centos specific dockerfile all named Dockerfile but in the context of the base OS branch(The name depends only on the configuration in container-index for example). I feel for our app it might bring-in a bit of complexities

But yes it might be a good option to keep it open. So we could probably take this approach make the base Dockerfile CentOS based and in future whenever we plan to support multiple OS we can dedicate a folder in our repo to maintain the separate base OS specific Dockerfile that way we can in a way recommend CentOS based image and also benefit from not having to replicate the same file twice in our repo and also support multiple base OS

@mohammedzee1000 @mitchharpur @miteshvp what do you suggest

**Comment by mohammedzee1000** [comment]
@dev-gaur @anmolbabu @mitchharpur @miteshvp I think i agree. It is not an absolute necessity to maintain multiple dockerfiles, unless you are going for a multii-os setup, which you probably arent at this point in time. We can look at that possibility later.

**Comment by anmolbabu** [comment]
Closing this PR as the PR to fix this has been merged..
Feel free to open a new bug when support for a new base OS needs to be added
