### ISSUE TITLE
Openshift Template must specify healthcheck and limits

### ISSUE THREAD

**Issue by mik-dass** [fabric8-hdd/supervisor#31]
As per the link: https://docs.google.com/document/d/14rKA_Uxve5f_mFNK4vhKhXrMcquiy25AQ5tpHJQwtbc/edit#heading=h.swasyl2uiw0o

**Comment by mik-dass** [comment]
- [x] Build the api /readiness and /liveness endpoints
- [x] Change the template to include the readiness and liveness health checks by pointing them to their respective api endpoints

For reference: 
https://docs.openshift.com/enterprise/3.1/dev_guide/application_health.html
https://github.com/fabric8-analytics/fabric8-analytics-server/blob/e633eaa68787d86766831335158e6ab21c9ec5da/bayesian/api_v1.py#L87

**Comment by anmolbabu** [comment]
Closing this issue as the PRs to fix this have been merged
