### ISSUE TITLE
Enable fabric8-hdd supervisor builds in centos-ci

### ISSUE THREAD

**Issue by anmolbabu** [fabric8-hdd/supervisor#34]
Ref: https://github.com/CentOS/container-index

**Comment by devang-gaur** [comment]
Hey Anmol, I forked this : https://github.com/fabric8-hdd/container-index

Now, the contributers have their own forks of the fabric8-hdd fork and send PRs to the same. After the merge, the PR can be raise to the main CentOS/container-index.

Maintains hierarchy and keeps the process organised. What do you think ?

**Comment by anmolbabu** [comment]
This involves 2 merges for the same PR and introduces latency.
The PR raised directly on the target repo is also reviewed right Please note the changes to this repo are very less frequent(only when we add a new repo under our hdd umbrella or when we need a new branch to be built)?
So, do you feel this is required? Or if its a standard practice across teams we can follow it

**Comment by anmolbabu** [comment]
But it might still be good to have
And considering the flow will be not very frequently used we can probably go ahead with this approach from next time. But I think we might need to rebase this fork once the "approved PR" https://github.com/CentOS/container-index/pull/236 is merged.

**Comment by anmolbabu** [comment]
Closing this PR as the PR to fix this has been merged
