### ISSUE TITLE
errors in Makefile

### ISSUE THREAD

**Issue by devang-gaur** [fabric8-hdd/supervisor#5]
1.) When I run Makefile, I get error : Makefile:13: *** missing separator.  Stop.

2.) No mention of dependency for fast-docker-build-tests stage in the Makefile

https://github.com/fabric8-hdd/supervisor/blob/8471815b73c2b6a0ec969aee22799fa695e5ea84/Makefile#L18

I know its not required as the docker-build (anmolbabu/supervisor) image would already be present. 
But, If you'd execute fast-docker-build-tests at first, without running any docker-build stage, it'd crash AFAIK.

Its a good measure, anyway.

**Comment by anmolbabu** [comment]
@dev-gaur Why is it required to make 1 docker build depend on another docker build?
Ideally I feel it should not be dependent for any reason?
Given https://github.com/fabric8-hdd/supervisor/issues/3

@miteshvp what do you suggest?

**Comment by anmolbabu** [comment]
#3 is required because unit-tests are code logic tests unlike functional tests that involve integration aspects of different components of code. A classic case is the one that you pointed here that docker build of test should not and cannot depend on docker build of the source...

I might be wrong but @miteshvp kindly correct us

**Comment by devang-gaur** [comment]
Hey Anmol, the Dockerfile.tests file inherits from anmolbabu/supervisor image.  Adding the dependency of docker-build or fast-docker-build would ensure the presence of the anmolbabu/supervisor docker image in the docker image repository. Like I said, its a good measure.

Also, in the long run, the repository account might be a a third party account or maybe someone who clones the repo and run the code might want to use their own docker image repository and account.

**Comment by anmolbabu** [comment]
@dev-gaur aah ok got it I was probably thinking something else.. Good catch

**Comment by anmolbabu** [comment]
Closing this issue as the PR to fix this has been merged..

**Comment by devang-gaur** [comment]
+1
